#!/bin/bash
# Deploy to Vercel via GitHub Integration

echo "🎯 Vercel部署指南"
echo "==============="
echo ""
echo "方式1: GitHub自动部署 (推荐)"
echo "----------------------------"
echo "1. 访问: https://vercel.com/new"
echo "2. 选择: Import Git Repository"
echo "3. 选择: cynthiaxu0529-art/fluxa-gacha"
echo "4. 配置:"
echo "   - Framework Preset: Other"
echo "   - Build Command: echo 'No build needed'"
echo "   - Output Directory: ."
echo "5. 点击: Deploy"
echo ""
echo "方式2: Vercel CLI"
echo "----------------"
echo "npm i -g vercel"
echo "vercel --yes"
echo ""
echo "方式3: Cloudflare Pages (免费替代)"
echo "--------------------------------"
echo "1. 访问: https://dash.cloudflare.com"
echo "2. Pages → Connect GitHub"
echo "3. 选择仓库: fluxa-gacha"
echo "4. 部署"
echo ""

echo "📋 部署后配置:"
echo "- 域名: gacha.fluxapay.xyz → Vercel项目"
echo "- 环境变量: 可选"
echo ""

echo "🔗 直接访问:"
echo "- Vercel: https://fluxa-gacha.vercel.app"
echo "- GitHub: https://github.com/cynthiaxu0529-art/fluxa-gacha"
